/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SensorReading = IDL.Record({
  'pH' : IDL.Float64,
  'temperature' : IDL.Float64,
  'glucose' : IDL.Float64,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addReading' : IDL.Func([SensorReading], [], []),
  'getAllReadings' : IDL.Func([], [IDL.Vec(SensorReading)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SensorReading = IDL.Record({
    'pH' : IDL.Float64,
    'temperature' : IDL.Float64,
    'glucose' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addReading' : IDL.Func([SensorReading], [], []),
    'getAllReadings' : IDL.Func([], [IDL.Vec(SensorReading)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };